### ISSUE TITLE
Why limit it to javascript files only?

### ISSUE THREAD

**Issue by Ziink** [albertromkes/tabout#1]
Very handy extension but why limit it to Javascript only?

**Comment by albertromkes** [comment]
You're absolutely right. Any suggestions about what languages to support? Maybe enable it for all languages except for text and markdown?

**Comment by Ziink** [comment]
I'd say enable it for all files but provide a command to enable/disable the extension itself.

**Comment by albertromkes** [comment]
Fixed in 0.1.0
