### ISSUE TITLE
rebind the hotkey to "enter" instead of "tab" button

### ISSUE THREAD

**Issue by erjan** [albertromkes/tabout#11]
tabout can't allow to rebind the actual hotkey to enter.

please enable it do so!

**Comment by brograhamer** [comment]
+1

**Comment by iYting** [comment]
+1

**Comment by linxiaoki** [comment]
+1

**Comment by snow212-cn** [comment]
The more we in urgent need for it, the more the author @albertromkes didn't give a shit about us

**Comment by albertromkes** [comment]
I'm sorry. I was under the impression that this was already possible. I'll try to have a look.

**Comment by albertromkes** [comment]
A quick google resulted in this: https://stackoverflow.com/a/42164950/1221887
Does that resolve your issue? @snow212-cn

**Comment by snow212-cn** [comment]
Little resolved. It took me years to find out the `keybingings.json` located 
`~/Library/Application Support/Code/User/keybindings.json`

**Comment by albertromkes** [comment]
Well, I'm glad that it is resolved now :) I'm gonna close this issue.
