### ISSUE TITLE
Breaks default tab completion

### ISSUE THREAD

**Issue by Lubits** [albertromkes/tabout#16]
The extension seems to break/override the default Tab Completion option in VSCode.

**Expected:**
Type: pr
Press: TAB
Get: print
Press: TAB
Get: println

**Actual:**
Instead of println I just insert a TAB character.

When I toggle Tabout it still doesn't work. However, when I disable tabout and reload the workspace the vscode tab completion works again.

**Comment by albertromkes** [comment]
Can't reproduce it. Probably fixed by upgrading to the newest version.
