### ISSUE TITLE
Code completion hint box is too wide

### ISSUE THREAD

**Issue by huzi19861007** [albertromkes/tabout#17]
The tabout for Pycharm platform code completion hint box width is too wide.

**Comment by albertromkes** [comment]
I have no clue what you're talking about. Pycharm is completely different editor than VSCode right? What am I missing?

**Comment by huzi19861007** [comment]
@albertromkes I mean, the tabout works normally on vscode, but on pycharm, the width of its code completion hint box is too wide, I use pycharm 2019.3.3. The previous version worked fine, but this problem happened after the plugin updated the latest version.

**Comment by albertromkes** [comment]
I didn't know that a VSCode extension could be used in Pycharm! Anyway, I have no clue why this happens with the latest version. I am not going to investigate why this is the case as I developed this for my own use and for VSCode. You could fork this extension and adjust it to work with Pycharm. Goodluck!
