### ISSUE TITLE
Overrides default tab completion

### ISSUE THREAD

**Issue by Aedaeum** [albertromkes/tabout#2]
As the title suggests, this extension breaks code completion using TAB. I'm on version 0.10.8.

**Comment by meritozh** [comment]
same issue

**Comment by piotrwitek** [comment]
very usefull extension, but as already mentioned it breaks default code completion, what I would suggest is to change trigger action to `shift + tab`, this binding is available

**Comment by litera** [comment]
It's not just about code completion but also when you i.e. edit HTML files and would add an HTML element's attribute by writing `attribute="` normally both quotes would be added and cursor would be placed within. but with TabOut installed only one is being added. I find that annoying too. So basically this is also some kind of *code completeion* as well...
