### ISSUE TITLE
I don't get it

### ISSUE THREAD

**Issue by yairEO** [albertromkes/tabout#24]
stared at the README gif while it looped 20 times and have no idea what this does.

The README explanation is not helping... could you please explain it to me? Thanks!

**Comment by albertromkes** [comment]
You're right: the gif isn't very helpful. It only shows how to disable/enable this extension. But, to my defense: it's hard to show this extension in a gif :). This extension allows you (the programmer) to press the `Tab` key when the caret is in front- or just after a special character. (A special character would be a parenthesis, a semicolon, a colon, etc.) When pressing `Tab` the caret will then jump over the special character. Or it will jump to the corresponding closing special character.  I am very used to this IDE behavior (Visual Studio has it build in), but Visual Studio Code did not provide it out-of-the-box. 

Hopefully this clarifies it a bit.

**Comment by abulka** [comment]
@albertromkes I think it would be helpful to new users if you simply copied and pasted your explanation above into the readme - no need for a gif! I got stuck figuring out how this extension behaved, too. 

Also, listing the special characters would be helpful - looking at the [source](https://github.com/albertromkes/tabout/blob/master/src/charactersToTabOutFrom.ts) they seem to be 

    [ { ( \ " : = > < .  ; ` '

though interestingly `'` is not listed in that source file yet that character does of course work with tabout.

**Comment by wjandrea** [comment]
@albertromkes FYI, someone on Super User was also confused: [What does it mean to "tab out" in an IDE/text editor?](https://superuser.com/questions/1756133/what-does-it-mean-to-tab-out-in-an-ide-text-editor)

I agree, adding a description would help.
