### ISSUE TITLE
conflicts with bracket pair colorizer 2

### ISSUE THREAD

**Issue by TyceHerrman** [albertromkes/tabout#26]
When tabout is enabled, bracket pair colorizer 2 formatting is not applied to python code.

VS Code 
- v1.50.1
- OS: Windows_NT x64 10.0.18362

Bracket pair Colorizer
- v0.2.0

**Comment by Stanzilla** [comment]
works fine here

**Comment by SiJiL82** [comment]
Bracket Pair Colorizer 2 is also no longer required, it's built into VSCode now.
