### ISSUE TITLE
Conflict with Emmet

### ISSUE THREAD

**Issue by imbwaldo** [albertromkes/tabout#3]
Thanks so much for developing this extension. I use WebStorm and love it … except for Jetbrains' refusal to add the Tabout feature to their IDEs. Your extension has made working with VSCode a real treat.

Anyway, I've had difficulty getting Emmet to function properly. For example, I key in "html:5" and hit TAB and nothing happens. Disabling Tabout fixed the problem.

But I love Tabout, so I'm very conflicted right now.

Thanks again.

_bryan

**Comment by albertromkes** [comment]
Check out the newest version (0.1.2). I don't use Emmet, but maybe this fix also resolves your issue.

**Comment by imbwaldo** [comment]
Sorry for the slow reply, Albert — and thanks for your quick one! I'll take a look at the newest version and see if that takes care of things.

**Comment by imbwaldo** [comment]
0.1.3 didn't fix the problem. I can still use the command palette, though, to run the emmet "Expand Abbreviation" command.
