### ISSUE TITLE
conflicts with github copilot completions

### ISSUE THREAD

**Issue by abulka** [albertromkes/tabout#31]
This extension conflicts with copilot.

Hitting `tab` to get a code completion from [codepilot](https://copilot.github.com/) fails - nothing happens, even though the grey prompt of suggested text is there.

I had to uninstall `tabout`. Even so, copilot was still not working and I was getting `command 'tabout' not found` when hitting tab. I had to find the key binding and remove it manually, and now copilot works again.

**Comment by abramyangCN** [comment]
> This extension conflicts with copilot.
> 
> Hitting `tab` to get a code completion from [codepilot](https://copilot.github.com/) fails - nothing happens, even though the grey prompt of suggested text is there.
> 
> I had to uninstall `tabout`. Even so, copilot was still not working and I was getting `command 'tabout' not found` when hitting tab. I had to find the key binding and remove it manually, and now copilot works again.

@abulka simply add a 'when expression' to your tabout keybinding:
``` !inlineSuggestionVisible```
![image](https://user-images.githubusercontent.com/19504192/127306325-ebb6eadd-544b-4d9a-a9c0-5d826732e26f.png)

**Comment by melMass** [comment]
@albertromkes Maybe make it the default!

https://github.com/microsoft/vscode/issues/130674

**Comment by bala0406** [comment]
I have found out the conflicting extension with the co-pilot. I completely disabled all the extensions first and the autocomplete was working. Then I enabled one at a time and checked whether the autocompletion with tab is working or not. Guess what, In my case, the conflicting extension was [Windows Default Keybindings](https://marketplace.visualstudio.com/items?itemName=smcpeak.default-keys-windows). Now hitting tab autocomplete flawlessly!

**Comment by melMass** [comment]
> I have found out the conflicting extension with the co-pilot. I completely disabled all the extensions first and the autocomplete was working. Then I enabled one at a time and checked whether the autocompletion with tab is working or not. Guess what, In my case, the conflicting extension was [Windows Default Keybindings](https://marketplace.visualstudio.com/items?itemName=smcpeak.default-keys-windows). Now hitting tab autocomplete flawlessly!

You are on the wrong issue

**Comment by bala0406** [comment]
> > I have found out the conflicting extension with the co-pilot. I completely disabled all the extensions first and the autocomplete was working. Then I enabled one at a time and checked whether the autocompletion with tab is working or not. Guess what, In my case, the conflicting extension was [Windows Default Keybindings](https://marketplace.visualstudio.com/items?itemName=smcpeak.default-keys-windows). Now hitting tab autocomplete flawlessly!
> 
> @bala0406 You are on the wrong issue

Sorry, my bad.

**Comment by melMass** [comment]
@bala0406 No problem, but delete it to avoid pollution

**Comment by albertromkes** [comment]
Should be fixed by #32

**Comment by CodeNameNinja** [comment]
For me it was editing editor.action.inlineSuggest.commit in the key bindings

![image](https://user-images.githubusercontent.com/35192626/132385661-2cdfaf3b-fe18-47b3-8e21-53662b650d13.png)

**Comment by melMass** [comment]
> For me it was editing editor.action.inlineSuggest.commit in the key bindings
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/35192626/132385661-2cdfaf3b-fe18-47b3-8e21-53662b650d13.png)

Not related to tabout then...
