### ISSUE TITLE
Doesn't work on my computer

### ISSUE THREAD

**Issue by edfarrerabp** [albertromkes/tabout#34]
I have MacBook Pro and after installing and then restarting vscode It's not working. I see the toggle message and the keybindings so I assume that it installed correctly. Any suggestions?

**Comment by albertromkes** [comment]
The only thing I can think of is some other extension that's interfering with TabOut. Can you try to disable other extensions and try again?

**Comment by matefriedl** [comment]
To me it seems like the [Markdown All in One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one) extension tends to break tabout (and [leaper](https://marketplace.visualstudio.com/items?itemName=OnlyLys.leaper)as well which has very similar functionality).

**Comment by FINDarkside** [comment]
Is this only supposed to work if your caret is at start of the string? Because that's how it works for me. If I'm in middle of string it'll just insert tab instead of jump out of it.

**Comment by PaoloJN** [comment]
its not working for me either. I tried disabling every extinction I have and still it inserts space instead of jumping out of brackets.

**Comment by FINDarkside** [comment]
Looking at the code, it seems like that's how it's supposed to work - only do something different if previous character is [one of these](https://github.com/albertromkes/tabout/blob/master/src/charactersToTabOutFrom.ts). I thought it would allow me to jump out of any string by pressing tab. I think the description should be more clear and that gif should show how this extension works instead of how to toggle it on/off.

**Comment by duckpuppy** [comment]
The extension still doesn't work for me (also on macOS). I can be just inside an opening `{` and press tab and it just inserts a tab character.

**Comment by edfarrerabp** [comment]
Forgot to comment on this but now the extension is working as intended. I went into keybindings and removed other keybindings that also used tab, restarted vscode and now it works. I reseted the removed keybindings and it still works

**Comment by Madd0g** [comment]
I tried disabling every other "Tab" binding, it only works for me when my cursor is at the beginning of the string or touching a brace or something.

I even tried disabling the vim plugin, just to see if that'd change anything.

Is it supposed to work when the cursor in the middle of a string?
