### ISSUE TITLE
Conflict with code snippet tab stops

### ISSUE THREAD

**Issue by vilic** [albertromkes/tabout#4]

**Comment by fronteed** [comment]
This package is extremely helpful, but it makes Tab expansion in Emmet broken.

**Comment by aga5tya** [comment]
> This package is extremely helpful, but it makes Tab expansion in Emmet broken.

Emmet is still broken on HTML files, other tab expansions like snippets are working fine anyways. Really good extension and would love if the emmet expansion gets fixed. Thanks @albertromkes

**Comment by bbugh** [comment]
FYI C# and JavaScript are also affected, not just Emmet.

**Comment by Mkayxx** [comment]
Its really frustrating when i try to if,else for,etc etc

**Comment by gaetawoo** [comment]
@vilic @fronteed @aga5tya @bbugh @koutselakismanos @albertromkes 

To everyone here, adding the following to your _keybindings.json_ file will fix this behavior. You'll be able to have Tabout enabled **AND** cycle through snippet tab stops:
```
[
{ "key": "tab","command": "-tabout",
"when": "editorTextFocus && !suggestWidgetVisible"},
{ "key": "tab","command": "tabout",
"when": "editorTextFocus && !suggestWidgetVisible && !inSnippetMode"} 
]
```
