### ISSUE TITLE
keyboard shortcut to temporarily disable tabout functinality

### ISSUE THREAD

**Issue by devinschumacher** [albertromkes/tabout#40]
is there a keyboard shortcut to temporarily disable tabout functionality if i was wanting to actually insert a tab somewhere?

(without having to shift+cmd+p to the menu and disable it all together

**Comment by jamesonknutson** [comment]
The command to toggle the extension seems to be [`toggle-tabout`](https://github.com/albertromkes/tabout/blob/5795cac6b796c0fddeb75a8a742a05f085c71d88/package.json#L42), so you should be able to insert something like this to your VSCode keybindings.json file:

```
{
    "key": "ctrl+shift+tab",
    "command": "toggle-tabout",
    "when": "editorTextFocus && !suggestWidgetVisible && !inlineSuggestionVisible && !inSnippetMode && !editorHasMultipleSelections"
}
```

In my example, the `when` context is copied from the same `when` context that the tabout functionality is enabled in, so this shortcut would only be available when you'd be in a spot where you'd be able to use tabout originally. You can discard the when context if that's not an important thing for you.
