### ISSUE TITLE
Is this Project accepting contributors?

### ISSUE THREAD

**Issue by jamesonknutson** [albertromkes/tabout#41]
I find this extension quite useful and have written a few of my own VSCode Extensions, specifically ones somewhat similar to this extension.

I would like to implement some of the changes that have been suggested in the open issues, but there has not been any activity on this repository for quite some time. Should I fork this repo, or should I contribute here?

@albertromkes

**Comment by albertromkes** [comment]
he @jamesonknutson, contributions are accepted and appreciated! I'll have a look as soon as possible!
