### ISSUE TITLE
tabout extension from visual Studio not available

### ISSUE THREAD

**Issue by Ad3901** [albertromkes/tabout#44]
Hi,

From comments I've seen online, it seems that the tabout extension should be available from the Visual Studio marketplace (accessed and installed through the extension manager like other extensions), but it doesn't show from there. I've also seen some instructions for loading it outside of the Visual Studio extension manager, but no luck with that as well.

I'm using Visual Studio Community 2022 Preview.

Can anyone explain what the problem might be, or provide instructions that might work?

Thanks for your help!

**Comment by albertromkes** [comment]
Hi,

This extension only works in Visual Studio **Code**. This is NOT the same as Visual Studio (Community, Professional, etc). The latter is a full blown IDE. Visual Studio Code is a (lightweight?) editor.

**Comment by Ad3901** [comment]
Thank you. Are you aware of a similar extension that works with community?

**Comment by albertromkes** [comment]
No, but in Visual Studio you get the TAB-behavior this extension provides Out Of the Box.
