### ISSUE TITLE
Extension does not work in a markdown list

### ISSUE THREAD

**Issue by werunom** [albertromkes/tabout#48]
Hello! Thanks for the extension!

Want to report that the extension does not work when the extension `Markdown All in One` by @yzhang-gh is enabled, especially inside a markdown list. See the recording below.

https://github.com/albertromkes/tabout/assets/24664855/4bb5e017-740e-49b6-8a69-86e85a784393

When the markdown extension is disabled, the tab-out works fine.

**Comment by yzhang-gh** [comment]
This is as expected. You can delete the Markdown All in One's keybinding of `tab` with VS Code's keybinding editor. (It is used to indent a Markdown list.)

**Comment by werunom** [comment]
@yzhang-gh Thanks for pointing out the problem. I cannot disable Markdown keybinding as I use `tab` frequently for intending. Will see whether I can map alternate keystrokes.
