### ISSUE TITLE
Can't indent line with TAB in html

### ISSUE THREAD

**Issue by kziajor** [albertromkes/tabout#5]
When I place cursor on line beginning and press TAB then instead of line indent cursor move into html tag. It's looks like TAB skip "<" char which in my opinion should be ignored. This extension should be used to TabOut from tags, strings, etc. Not to TabIN to them.

**Comment by joshpeng** [comment]
It seems to be tabbing in on any line that starts with one of the defined character sets. So all the quotes, brackets, and parenthesis seem to be effected not limited to in HTML files. Would be greatly appreciated to get a fix.

**Comment by albertromkes** [comment]
Please update to the latest version
