### ISSUE TITLE
Breaks emmet tab completion

### ISSUE THREAD

**Issue by ferhtgoldaraz** [albertromkes/tabout#9]
**Steps to reproduce**

1. Disable all plugins but tabOut.
2. Create an `index.html` file.
3. Input a `!` at the begining of the file.
4. Press tab

**Expected**

The following markup should appear:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  
</body>
</html>
```

**Actual**

Nothing happens.

**Comment by bitfed** [comment]
This breaks emmet for me as well.  Which is almost as big a dent in my productivity as TabOut provides, so I can't use it.

If I could just disable it for html / html files I would be happy since essentially emmet includes what TabOut does already.

**Comment by nealoke** [comment]
+1 emmet > tabOut in productivity yet it would be nice to combine them :(

**Comment by misaizdaleka** [comment]
+1

**Comment by albertromkes** [comment]
Just tested it as well. Issue is resolved.
